powerpc/vas: Implement VAS_842_TX_WIN_OPEN ioctl
This is useful for testing submitting CRBs from user space to the
NX engines. NX-842 is not offically supported for user space.

For simplicity, we piggy back on the FTW driver for testing.

Status: Further, are some TODOs in vas-fault.c (specially ensuring
	process is alive before trying to kill it or copy_to_user().

	Seems to work often, but intermittently we get Translation error
	(using the user-nx-test1 selftest from a follow-on commit). That
	needs to be debugged.

	user-nx-test1: Test Info:
	842: Compress/decompress data and compare results
		 Page size 65536
		 Buffer size 65536
		 Buffer Align 256
		 CRC Enabled
	Window paste addr @0x7fffa4900000
	Source DDE @ 0x29e50410
		 flags 0x0, count 0, index 0, len 65536, addr 0x29e20100
	Target DDE @ 0x29e50420
		 flags 0x0, count 0, index 0, len 65536, addr 0x29e40300
	CRB 0x29e50400, CSB 0x29e50470 [BE 7004e52900000000]
	Paste attempt 1/5 returns 0x2
	ERROR: Translation error at 1e22900000000 : 80 00 05 40 00000000
	wait_for_csb() returns -71
	nx_function returns -71, errno 0

Signed-off-by: Sukadev Bhattiprolu <sukadev@linux.vnet.ibm.com>